name: aiandml_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - rapidsai
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - aom=3.6.1
  - attr=2.5.2
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backports.zstd=1.3.0
  - bokeh=3.8.1
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cachetools=6.2.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - cloudpickle=3.1.2
  - contourpy=1.3.2
  - cpython=3.10.19
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-crt-dev_linux-64=12.9.41
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvcc-dev_linux-64=12.9.41
  - cuda-nvcc-impl=12.9.41
  - cuda-nvcc-tools=12.9.41
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-nvvm-dev_linux-64=12.9.41
  - cuda-nvvm-impl=12.9.41
  - cuda-nvvm-tools=12.9.41
  - cuda-opencl=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-python=12.6.0
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - cudf=24.12.00
  - cudnn=9.14.0.64
  - cuml=24.12.00
  - cupy=13.6.0
  - cupy-core=13.6.0
  - cytoolz=1.1.0
  - dask=2024.11.2
  - dask-core=2024.11.2
  - dask-cuda=24.12.00
  - dask-cudf=24.12.00
  - dask-expr=1.1.19
  - distributed=2024.11.2
  - distributed-ucxx=0.41.00
  - dlpack=0.8
  - fastrlock=0.8.3
  - ffmpeg=4.4.2
  - filelock=3.20.2
  - fmt=11.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcudf=24.12.00
  - libcudnn=9.14.0.64
  - libcudnn-dev=9.14.0.64
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcuml=24.12.00
  - libcumlprims=24.12.00
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcuvs=24.12.00
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.32.0
  - libgoogle-cloud-storage=2.32.0
  - libgrpc=1.67.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - libkvikio=24.12.01
  - liblapack=3.11.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.30
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libprotobuf=5.28.2
  - libraft=24.12.00
  - libraft-headers=24.12.00
  - libraft-headers-only=24.12.00
  - libre2-11=2024.07.02
  - librmm=24.12.01
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtasn1=4.20.0
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libtorch=2.5.1
  - libucxx=0.41.00
  - libudev1=258.3
  - libunistring=0.9.10
  - libutf8proc=2.9.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvpx=1.13.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - narwhals=2.14.0
  - nccl=2.28.9
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - numba=0.60.0
  - numba-cuda=0.0.17.1
  - numpy=1.26.4
  - nvcomp=4.1.0.6
  - nvtx=0.2.14
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.3.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - orc=2.0.3
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.2.3
  - partd=1.4.2
  - pillow=12.1.0
  - pip=25.3
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pygments=2.19.2
  - pylibcudf=24.12.00
  - pylibraft=24.12.00
  - pynvjitlink=0.7.0
  - pynvml=11.4.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - raft-dask=24.12.00
  - rapids-dask-dependency=24.12.00
  - rdma-core=60.0
  - re2=2024.07.02
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - rmm=24.12.01
  - s2n=1.5.11
  - scipy=1.12.0
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - spdlog=1.14.1
  - svt-av1=1.4.1
  - sympy=1.14.0
  - tbb=2021.13.0
  - tblib=3.2.2
  - tk=8.6.13
  - toolz=1.1.0
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.4
  - treelite=4.3.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucx=1.17.0
  - ucx-py=0.41.00
  - ucxx=0.41.00
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cffi==2.0.0
      - cfgv==3.5.0
      - chromadb==1.1.1
      - click==8.1.8
      - coloredlogs==15.0.1
      - crewai==1.7.2
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - docstring-parser==0.17.0
      - durationpy==0.10
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - flatbuffers==25.12.19
      - frozenlist==1.8.0
      - google-auth==2.45.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - identify==2.6.15
      - importlib-resources==6.5.2
      - instructor==1.12.0
      - jiter==0.10.0
      - json-repair==0.25.3
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.6
      - langchain-text-splitters==1.1.0
      - langsmith==0.6.0
      - marshmallow==3.26.2
      - mcp==1.16.0
      - mmh3==5.2.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nodeenv==1.10.0
      - oauthlib==3.3.1
      - ollama==0.6.1
      - onnxruntime==1.23.2
      - openai==1.83.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-exporter-otlp-proto-http==1.34.1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - orjson==3.11.5
      - overrides==7.7.0
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - platformdirs==4.5.1
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - portalocker==2.7.0
      - posthog==5.4.0
      - pre-commit==4.5.1
      - propcache==0.4.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pyjwt==2.9.0
      - pypdfium2==5.2.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.21
      - referencing==0.37.0
      - regex==2024.9.11
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - sse-starlette==3.1.2
      - starlette==0.50.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tomli==2.0.2
      - tomli-w==1.1.0
      - tqdm==4.67.1
      - typer==0.21.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.3.0
      - uuid-utils==0.12.0
      - uv==0.9.21
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - virtualenv==20.35.4
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /home/shadowz/miniconda3/envs/aiandml_env
